### ISSUE TITLE
difference between CheetahRun and half-cheetah

### ISSUE THREAD

**Issue by randyhouse** [matsuolab/BREMEN#3]
Hi. I noticed that there are cheetah run and half-cheetah environments in this repo. 
What are the difference between the two environment?

**Comment by 1079658109** [comment]
hi! brother, can you run this code?could you help me?

**Comment by frt03** [comment]
@randyhouse The difference between CheetahRun and HalfCheetah in *this repo* is the type of reward function.
Maybe there are further differences between the original DM control CheetahRun and MuJoCo HalfCheetah (I recommend you to see the original source code).
